spring:
  cloud:
    gateway:
      global-cors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT



